"""Fast ASCII writer for OpenFOAM polyMesh files.

Writes points/faces/owner/neighbour/boundary with the FoamFile headers and
ordering conventions OpenFOAM v2506 expects.  Uses bulk NumPy string
formatting; an entire ~10^6-face mesh writes in a few seconds.
"""

from __future__ import annotations

import io
import logging
import re
from pathlib import Path

import numpy as np

from .polymesh import PolyMeshData

logger = logging.getLogger(__name__)

_HEADER = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by deepshapeopt.hexmesh (SDF-driven hex mesh pipeline)            |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    arch        "LSB;label=32;scalar=64";
    class       {cls};
{note}    location    "constant/polyMesh";
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

"""

_FOOTER = "\n\n// ************************************************************************* //\n"


def _header(cls: str, obj: str, note: str | None = None) -> str:
    note_line = f'    note        "{note}";\n' if note else ""
    return _HEADER.format(cls=cls, obj=obj, note=note_line)


def _bulk_lines(array: np.ndarray, fmt: str) -> str:
    buf = io.StringIO()
    np.savetxt(buf, array, fmt=fmt)
    return buf.getvalue()


def write_polymesh(mesh: PolyMeshData, case_dir: Path, scale: float = 1.0) -> Path:
    """Write the full polyMesh into ``case_dir/constant/polyMesh``.

    ``scale`` multiplies the point coordinates on write (e.g. 0.001 for
    configs in millimetres feeding a case that runs in metres -- the
    blockMesh ``scale`` equivalent).
    """
    out = Path(case_dir) / "constant" / "polyMesh"
    out.mkdir(parents=True, exist_ok=True)

    n_points = len(mesh.points)
    n_faces = len(mesh.faces)
    n_internal = mesh.n_internal_faces
    note = (
        f"nPoints:{n_points}  nCells:{mesh.n_cells}  "
        f"nFaces:{n_faces}  nInternalFaces:{n_internal}"
    )

    with open(out / "points", "w") as f:
        f.write(_header("vectorField", "points"))
        f.write(f"{n_points}\n(\n")
        f.write(_bulk_lines(mesh.points * scale, "(%.16g %.16g %.16g)"))
        f.write(")")
        f.write(_FOOTER)

    with open(out / "faces", "w") as f:
        f.write(_header("faceList", "faces"))
        f.write(f"{n_faces}\n(\n")
        f.write(_bulk_lines(mesh.faces, "4(%d %d %d %d)"))
        f.write(")")
        f.write(_FOOTER)

    with open(out / "owner", "w") as f:
        f.write(_header("labelList", "owner", note))
        f.write(f"{n_faces}\n(\n")
        f.write(_bulk_lines(mesh.owner[:, None], "%d"))
        f.write(")")
        f.write(_FOOTER)

    with open(out / "neighbour", "w") as f:
        f.write(_header("labelList", "neighbour", note))
        f.write(f"{n_internal}\n(\n")
        f.write(_bulk_lines(mesh.neighbour[:, None], "%d"))
        f.write(")")
        f.write(_FOOTER)

    with open(out / "boundary", "w") as f:
        f.write(_header("polyBoundaryMesh", "boundary"))
        f.write(f"{len(mesh.patches)}\n(\n")
        for p in mesh.patches:
            f.write(f"    {p.name}\n    {{\n")
            f.write(f"        type            {p.type};\n")
            if p.in_groups:
                groups = " ".join(p.in_groups)
                f.write(f"        inGroups        {len(p.in_groups)}({groups});\n")
            f.write(f"        nFaces          {p.n_faces};\n")
            f.write(f"        startFace       {p.start};\n")
            f.write("    }\n")
        f.write(")")
        f.write(_FOOTER)

    logger.debug("Wrote polyMesh to %s", out)
    return out


def write_points_only(mesh: PolyMeshData, case_dir: Path, scale: float = 1.0) -> Path:
    """Rewrite only the points file (fast path: unchanged connectivity)."""
    out = Path(case_dir) / "constant" / "polyMesh"
    if not (out / "faces").exists():
        raise FileNotFoundError(f"Cannot update points: no polyMesh in {out}")
    with open(out / "points", "w") as f:
        f.write(_header("vectorField", "points"))
        f.write(f"{len(mesh.points)}\n(\n")
        f.write(_bulk_lines(mesh.points * scale, "(%.16g %.16g %.16g)"))
        f.write(")")
        f.write(_FOOTER)
    return out


# ---------------------------------------------------------------------------
# checkMesh gate
# ---------------------------------------------------------------------------

def checkmesh_log_ok(log_text: str) -> tuple[bool, list[str]]:
    """Parse a checkMesh log; returns (ok, failed check descriptions)."""
    failed: list[str] = []
    for line in log_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("***"):
            failed.append(stripped.lstrip("*").strip())
    m = re.search(r"Failed (\d+) mesh checks", log_text)
    if m and int(m.group(1)) > 0:
        return False, failed
    if "Mesh OK." in log_text:
        return True, failed
    # No verdict found: treat as failure so problems never pass silently.
    return False, ["checkMesh log contains no verdict (crashed?)"]
